export const testimonials = [
  {
    id: 1,
    name: "John Doe",
    review: "Amazing experience!",
    stars: 5,
    img: "https://static.vecteezy.com/system/resources/previews/043/473/489/non_2x/smiling-teenage-boy-with-laptop-standing-isolated-on-transparent-png.png",
  },
  {
    id: 2,
    name: "Sarah Mason",
    review: "Great course, highly recommend!",
    stars: 4,
    img: "path-to-image-2",
  },
  {
    id: 3,
    name: "Maria Silva",
    review: "Learned a lot!",
    stars: 4,
    img: "https://img.freepik.com/free-photo/man-with-thumb-up_1368-3701.jpg?size=626&ext=jpg&ga=GA1.1.1890765304.1711517804&semt=ais_hybrid",
  },
  {
    id: 4,
    name: "Caroline White",
    review: "Life-changing course!",
    stars: 5,
    img: "path-to-image-4",
  },
  {
    id: 5,
    name: "Nathan Baker",
    review: "Good value for money.",
    stars: 4,
    img: "https://static.vecteezy.com/system/resources/previews/043/473/489/non_2x/smiling-teenage-boy-with-laptop-standing-isolated-on-transparent-png.png",
  },
  {
    id: 6,
    name: "Liam Scott",
    review: "Highly recommended for beginners.",
    stars: 5,
    img: "path-to-image-6",
  },
  {
    id: 7,
    name: "Olivia Harris",
    review: "Practical and insightful.",
    stars: 4,
    img: "path-to-image-7",
  },
  {
    id: 8,
    name: "Noah Moore",
    review: "Fantastic support throughout!",
    stars: 5,
    img: "path-to-image-8",
  },
  {
    id: 9,
    name: "Sophia Lee",
    review: "Loved the hands-on approach.",
    stars: 5,
    img: "path-to-image-9",
  },
  {
    id: 10,
    name: "James Brown",
    review: "Could use more advanced content.",
    stars: 3,
    img: "https://static.vecteezy.com/system/resources/previews/043/473/489/non_2x/smiling-teenage-boy-with-laptop-standing-isolated-on-transparent-png.png",
  },
  {
    id: 11,
    name: "Sophia Lee",
    review: "Loved the hands-on approach.",
    stars: 5,
    img: "path-to-image-9",
  },
  {
    id: 12,
    name: "James Brown",
    review: "Could use more advanced content.",
    stars: 3,
    img: "path-to-image-10",
  },
  {
    id: 13,
    name: "Caroline White",
    review: "Life-changing course!",
    stars: 5,
    img: "path-to-image-4",
  },
];